jwt:
  signerKey: "ic+avxLvVv1qh3dGR/3LTAGv0AWaPUOP5G0aYqGwhXmuIia9xe9/wM5fuZyOtWq2"
  valid-duration: 7200
  refreshable-duration: 720000

sendgrid:
#  api-key: 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
  api-key: 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
  from-email: phantuanviet0706@gmail.com