package com.example.pancharm.service;

import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

import com.example.pancharm.constant.ErrorCode;
import com.example.pancharm.dto.request.product.*;
import com.example.pancharm.dto.response.base.PageResponse;
import com.example.pancharm.dto.response.product.*;
import com.example.pancharm.entity.*;
import com.example.pancharm.exception.AppException;
import com.example.pancharm.mapper.*;
import com.example.pancharm.repository.*;
import com.example.pancharm.service.product.ProductService;
import com.example.pancharm.util.*;

import java.util.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;

public class ProductServiceTest {

    @Mock ProductRepository productRepository;
    @Mock ProductMapper productMapper;
    @Mock ProductImageRepository productImagesRepository;
    @Mock CategoryRepository categoryRepository;
    @Mock PageMapper pageMapper;
    @Mock ImageUtil imageUtil;
    @Mock GeneralUtil generalUtil;

    @InjectMocks
    ProductService productService;

    @BeforeEach
    void setup() {
        MockitoAnnotations.openMocks(this);
    }


    @Test
    void createProduct_Success_WhenSlugNotExists() {
        ProductCreationRequest request = new ProductCreationRequest();
        request.setSlug("slug-123");
        request.setCategoryId(1);

        Products product = new Products();
        product.setId(42);

        Categories category = new Categories();

        when(productRepository.existsBySlug("slug-123")).thenReturn(false);
        when(productMapper.toProduct(request)).thenReturn(product);
        when(categoryRepository.findById("1")).thenReturn(Optional.of(category));
        doNothing().when(imageUtil).attachImages(any(), eq(product), eq("products"), any(), any());
        when(productRepository.save(product)).thenReturn(product);
        when(generalUtil.generateSlug(anyString(), anyInt())).thenReturn("generated-slug"); // unused here since slug present
        when(productMapper.toProductResponse(product)).thenReturn(new ProductDetailResponse());

        ProductDetailResponse response = productService.createProduct(request);

        assertNotNull(response);
        verify(productRepository).existsBySlug("slug-123");
        verify(productRepository, times(2)).save(product);
        verify(imageUtil).attachImages(any(), eq(product), eq("products"), any(), any());
    }

    @Test
    void createProduct_Throws_WhenSlugExists() {
        ProductCreationRequest request = new ProductCreationRequest();
        request.setSlug("dup-slug");

        when(productRepository.existsBySlug("dup-slug")).thenReturn(true);

        AppException ex = assertThrows(AppException.class, () -> productService.createProduct(request));
        assertEquals(ErrorCode.SLUG_EXISTED, ex.getErrorCode());
    }

    @Test
    void createProduct_Throws_WhenCategoryNotFound() {
        ProductCreationRequest request = new ProductCreationRequest();
        request.setSlug("slug");
        request.setCategoryId(99);

        when(productRepository.existsBySlug("slug")).thenReturn(false);
        when(productMapper.toProduct(request)).thenReturn(new Products());
        when(categoryRepository.findById("99")).thenReturn(Optional.empty());

        AppException ex = assertThrows(AppException.class, () -> productService.createProduct(request));
        assertEquals(ErrorCode.CATEGORY_NOT_FOUND, ex.getErrorCode());
    }

    @Test
    void createProduct_Throws_WhenSaveFails() {
        ProductCreationRequest request = new ProductCreationRequest();
        request.setSlug(null);
        request.setCategoryId(1);

        Products product = new Products();

        Categories category = new Categories();

        when(productRepository.existsBySlug(anyString())).thenReturn(false);
        when(productMapper.toProduct(request)).thenReturn(product);
        when(categoryRepository.findById("1")).thenReturn(Optional.of(category));
        doThrow(new DataIntegrityViolationException("")).when(productRepository).save(product);

        AppException ex = assertThrows(AppException.class, () -> productService.createProduct(request));
        assertEquals(ErrorCode.UPDATE_ERROR, ex.getErrorCode());
    }

    @Test
    void createProduct_SlugAutoGenerated_WhenSlugIsNullOrBlank() {
        ProductCreationRequest request = new ProductCreationRequest();
        request.setSlug("  ");
        request.setCategoryId(1);

        Products product = new Products();
        product.setId(42);

        Categories category = new Categories();

        when(productRepository.existsBySlug(anyString())).thenReturn(false);
        when(productMapper.toProduct(request)).thenReturn(product);
        when(categoryRepository.findById("1")).thenReturn(Optional.of(category));
        doNothing().when(imageUtil).attachImages(any(), eq(product), eq("products"), any(), any());
        when(productRepository.save(product)).thenReturn(product);
        when(generalUtil.generateSlug("product", 42)).thenReturn("auto-slug");
        when(productMapper.toProductResponse(product)).thenReturn(new ProductDetailResponse());

        ProductDetailResponse response = productService.createProduct(request);

        assertNotNull(response);
        assertEquals("auto-slug", product.getSlug());
        verify(productRepository, times(2)).save(product);
    }


    @Test
    void updateProduct_Success() {
        int productId = 1;
        ProductUpdateRequest request = new ProductUpdateRequest();
        Set<ProductImages> existingImages = new HashSet<>();
        ProductImages oldImage = new ProductImages();
        oldImage.setPath("old/path");
        existingImages.add(oldImage);

        Products product = new Products();
        product.setImages(existingImages);

        when(productRepository.findById(productId)).thenReturn(Optional.of(product));
        doNothing().when(productMapper).updateProduct(request, product);
        doNothing().when(imageUtil).attachImages(any(), eq(product), eq("products"), any(), any());
        when(product.getImages()).thenReturn(new HashSet<>());  // simulate no images after attach

        doNothing().when(imageUtil).deletePaths(anyString());
        when(productRepository.save(product)).thenReturn(product);
        when(productMapper.toProductResponse(product)).thenReturn(new ProductDetailResponse());

        ProductDetailResponse response = productService.updateProduct(productId, request);

        assertNotNull(response);
        verify(productRepository).findById(productId);
        verify(imageUtil).deletePaths("old/path");
        verify(productRepository).save(product);
    }

    @Test
    void updateProduct_Throws_WhenProductNotFound() {
        when(productRepository.findById(1)).thenReturn(Optional.empty());

        AppException ex = assertThrows(AppException.class, () -> productService.updateProduct(1, new ProductUpdateRequest()));
        assertEquals(ErrorCode.PRODUCT_NOT_FOUND, ex.getErrorCode());
    }

    @Test
    void updateProduct_Throws_WhenSaveFails() {
        int productId = 1;
        ProductUpdateRequest request = new ProductUpdateRequest();
        Products product = new Products();

        when(productRepository.findById(productId)).thenReturn(Optional.of(product));
        doNothing().when(productMapper).updateProduct(request, product);
        doNothing().when(imageUtil).attachImages(any(), eq(product), eq("products"), any(), any());
        when(product.getImages()).thenReturn(new HashSet<>());

        doThrow(new DataIntegrityViolationException("")).when(productRepository).save(product);

        AppException ex = assertThrows(AppException.class, () -> productService.updateProduct(productId, request));
        assertEquals(ErrorCode.UPDATE_ERROR, ex.getErrorCode());
    }


    @Test
    void deleteProduct_Success() {
        int productId = 1;
        when(productRepository.existsById(productId)).thenReturn(true);
        doNothing().when(productRepository).deleteById(productId);

        productService.deleteProduct(productId);

        verify(productRepository).deleteById(productId);
    }

    @Test
    void deleteProduct_Throws_WhenNotFound() {
        when(productRepository.existsById(1)).thenReturn(false);

        AppException ex = assertThrows(AppException.class, () -> productService.deleteProduct(1));
        assertEquals(ErrorCode.PRODUCT_NOT_FOUND, ex.getErrorCode());
    }


    @Test
    void getProduct_Success() {
        int productId = 1;
        Products product = new Products();
        when(productRepository.findById(productId)).thenReturn(Optional.of(product));
        when(productMapper.toProductResponse(product)).thenReturn(new ProductDetailResponse());

        ProductDetailResponse resp = productService.getProduct(productId);

        assertNotNull(resp);
        verify(productRepository).findById(productId);
    }

    @Test
    void getProduct_Throws_WhenNotFound() {
        when(productRepository.findById(1)).thenReturn(Optional.empty());

        AppException ex = assertThrows(AppException.class, () -> productService.getProduct(1));
        assertEquals(ErrorCode.PRODUCT_NOT_FOUND, ex.getErrorCode());
    }


    @Test
    void getProducts_WithFilters() {
        ProductFilterRequest request = new ProductFilterRequest();
        request.setSlug("slug");
        request.setKeyword("keyword");
        request.setQuantityFrom(5);
        request.setQuantityTo(10);

        Pageable pageable = PageRequest.of(0, 10);
        Page<Products> page = new PageImpl<>(List.of(new Products()));
        when(PageRequestUtil.from(request)).thenReturn(pageable);
        when(productRepository.findAll(ArgumentMatchers.<Specification<Products>>any(), eq(pageable))).thenReturn(page);
        when(productMapper.toProductListResponse(any())).thenReturn(new ProductListResponse());
        when(pageMapper.toPageResponse(any())).thenReturn(new PageResponse<>());

        PageResponse<ProductListResponse> response = productService.getProducts(request);

        assertNotNull(response);
        verify(productRepository).findAll(any(Specification.class), any(Pageable.class));
        verify(pageMapper).toPageResponse(any());
    }

    @Test
    void getProducts_WithoutFilters() {
        ProductFilterRequest request = new ProductFilterRequest();

        Pageable pageable = PageRequest.of(0, 10);
        Page<Products> page = new PageImpl<>(List.of(new Products()));

        when(PageRequestUtil.from(request)).thenReturn(pageable);
        when(productRepository.findAll(ArgumentMatchers.<Specification<Products>>any(), eq(pageable))).thenReturn(page);
        when(productMapper.toProductListResponse(any())).thenReturn(new ProductListResponse());
        when(pageMapper.toPageResponse(any())).thenReturn(new PageResponse<>());

        PageResponse<ProductListResponse> response = productService.getProducts(request);

        assertNotNull(response);
        verify(productRepository).findAll(any(Specification.class), any(Pageable.class));
        verify(pageMapper).toPageResponse(any());
    }
}
